import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";

import "./globals.css";
import AuthProvider from "@/components/provider/AuthProvider";
import Header from "@/components/Header";

const notoSansKR = Noto_Sans_KR({ weight: ["300", "500"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "chat-app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={notoSansKR.className}>
        <AuthProvider>
          {/* <Header /> */}
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
